allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  vue-demi: true
overrides:
  axios: 1.18.1
  js-cookie: 3.0.8
  ua-parser-js: 1.0.34
  markdown-it: 14.2.0
minimumReleaseAgeExclude:
  - "@opendesign-plus/*"
  - "@opendesign-plus-test/*"
  - "@opensig/opendesign"
